env:
  NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
  NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
  NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
jobs:
  Deploy-To-INT:
    environment:
      name: Integration
    name: Deploy to Integration
    needs:
      - Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: c-hive/gha-yarn-cache@v2
      - env:
          ENV: int
          S3BUCKET: gsp-int-nextjs-bucket
          SERVERALIAS: gsp-nextjs-bp-int.nonprod.wmsports.io
        name: Install
        run: |
          yarn top-jfrog-login
          yarn install
          NODE_ENV=int yarn nx affected --target=build --base=$(git rev-parse @~) HEAD=$GITHUB_REF
          yarn nx affected --target=deploy --base=$(git rev-parse @~) HEAD=$GITHUB_REF --args="--env=int"
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: c-hive/gha-yarn-cache@v2
      - name: Running Test
        run: |
          yarn top-jfrog-login
          yarn
          yarn lint
          yarn test
name: Continious Integration
on:
  push:
    branches:
      - main
