name: Initial Setup
description: Initial composite action setup

inputs:
  npm_email: 
    description: 'npm email'
  npm_password: 
    description: 'npm password'
  npm_username: 
    description: 'npm username'

runs:
  using: "composite"
  steps:
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Cache yarn dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: git fetch origin main
      shell: bash
      name: Fetching git history
    - name: Installing packages
      env:
        NPM_EMAIL: ${{ inputs.npm_email }}
        NPM_PASSWORD: ${{ inputs.npm_password }}
        NPM_USERNAME: ${{ inputs.npm_username }}
      shell: bash
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |-
        yarn