web:
  component: '@sls-next/serverless-component@3.7.0-alpha.11'
  inputs:
    bucketName: beats-dev-nextjs-bucket
    build:
      args: ""
      cmd: ./build.sh
    cloudfront:
      aliases:
        - beats-nextjs-dev.testdomain.io
      certificate:
        acmCertificateArn: ""
      defaults:
        viewerProtocolPolicy: redirect-to-https
    domain:
      - beats-nextjs-dev
      - testdomain.io
    nextConfigDir: ../
